version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5003:5001"
    env_file:
      - .env
    environment:
      - SERVICE_ID=service2
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
