version: '3.8'

services:
  backend:
    image: song-service-backend
    build: .
    ports:
      - "5002:5001"
    env_file:
      - .env
    environment:
      - SERVICE_ID=service1
      - PEERS=service2,service3
      - MONGO_URI=mongodb://mongo:27017/song-service
    depends_on:
      - mongo
    networks:
      - backend1-network

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - backend1-network

networks:
  backend1-network:

volumes:
  mongo-data:
