version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5002:5001"
    env_file:
      - .env
    environment:
      - SERVICE_ID=service1
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: song-db
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
