version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5002:5001"
    environment:
      - PORT=5001
      - MONGO_URI=mongodb://mongo:27017/song-service
      - SECRET_KEY=secretkey
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: song-db
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
